[build-system]
requires = ["hatchling>=1.4.0", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[project]
name = "jupyter_ai_magics"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Jupyter",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dynamic = ["version", "description", "authors", "urls", "keywords"]

dependencies = [
    "ipython",
    "importlib_metadata>=5.2.0",
    "langchain>=0.2.17,<0.3.0",
    "langchain_community>=0.2.19,<0.3.0",
    "typing_extensions>=4.5.0",
    "click~=8.0",
    "jsonpath-ng>=1.5.3,<2",
]

[project.optional-dependencies]
dev = ["pre-commit>=3.3.3,<4"]

test = ["coverage", "pytest", "pytest-asyncio", "pytest-cov"]

all = []

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.hooks.version]
path = "jupyter_ai_magics/_version.py"
